config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = @post.id
    comment.user_id = current_user.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    post_comment = @post.post_comments.find(params[:id])
    post_comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment, :created_at)
  end

end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comment.html.erb
<div class="comment">
  <% @post.post_comments.each do |post_comment| %>
    <div>
      <%= link_to user_path(post_comment.user_id) do %>
        <%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "40x40", class: "hover10 mt-3 rounded-circle"; %>
        <%= post_comment.user.name %>
      <% end %>
    </div>
    <%= post_comment.created_at.in_time_zone('Tokyo') %><br>
    <%= post_comment.comment %>
    <% if post_comment.user == current_user %>
        <%= link_to post_post_comment_path(post_comment.post, post_comment), method: :delete,data: { confirm: '本当にコメントを削除しますか？' }, class: "destroy_post_comments#{@post.id}", remote: true do %>
          <i class="fas fa-minus-circle"></i>
        <% end %>
    <% end %>
  <% end %>
</div>
<%= form_with(model:[@post, @post_comment], remote: true) do |f| %>
  <div class="col-md-12"><br>
    <%= f.text_field :comment, placeholder: "コメントする" %>
    <%= f.submit "送信", class: 'btn_design btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/post_comments/create.js.erb
$('#comments_area').html("<%= j(render 'comment', post_comment) %>", );
$(".text_field").val("");

app/views/post_comments/destroy.js.erb
$('#comments_area').html("<%= j(render 'comment', post_comment) %>");