config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  #オーバーライド
  # def is_flashing_format?
  #   false
  # end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    flash[:success] = '会員情報が正常に登録されました｡'
    root_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # オーバーライド
   def is_flashing_format?
     false
   end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    flash[:info] = 'サインインに成功しました｡'
    root_path
  end

  def after_sign_out_path_for(resource)
    flash[:danger] = 'サインアウトに成功しました｡'
    root_path
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_puth(current_user)
    end
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), success: '会員情報が更新されました｡'
    else
      flash[:danger] = '会員情報の更新に失敗しました｡'
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if users.exists? %>
<table class="table table-hover">
  <thead class="table-dark">
    <tr class="follow">
      <th>image</th>
      <th>name</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
    </tr>
  </thead>

  <% users.each do |user| %>
    <tbody>
      <tr class="table-active">
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50", class:"hover10 mt-3 rounded-circle"; %>
          <% end %>
        </td>
        <td class="line" style="color: white;">
          <%= link_to user_path(user) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="line" style="color: white;">
          <%= link_to follows_user_path(user) do %>
          （ <%= user.followings.count %> ）
          <% end %>
        </td>
        <td class="line" style="color: white;">
          <%= link_to followers_user_path(user) do %>
          （ <%= user.followers.count %> ）
          <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>
<% else %>
  <p class="font" style="color: white;">ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<div class="img"><br>
  <div class='container mt-5'>
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="font" style="color: white;">〘 User Edit 〙</h2><br>
      </div>
    </div>

    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :ユーザー名 %>
            <%= f.text_field :name, class: "form-control name" %>
          </div><br>
          <div class="form-group">
            <%= f.label :プロフィール画像 %>
            <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
          </div><br>
          <div class="form-group">
            <%= f.label :自己紹介欄 %>
            <%= f.text_area :introduction, class: "form-control introduction"%>
          </div><br>
            <div class="btn_design" style="margin-bottom: 160px;">
              <%= f.submit "変更を保存", class: 'btn btn-success col-md-4' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="img">
  <div class="container"><br>
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="font" style="color: white; margin-top: 50px;">〘 Followers 〙</h2><br>
        <%= render "users/follow", users: @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="img">
  <div class="container"><br>
    <div class="row">
      <div class="col-md-12 text-center">
        <h2 class="font" style="color: white; margin-top: 50px;">〘 Follows 〙</h2><br>
        <%= render "users/follow", users: @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="img2"><br>
  <div class='container mt-5'>
    <div class="row">
      <div class="col-md-12 text-center">
        <% if user_signed_in? && current_user.id.to_s == params[:id] %>
          <h2 class="font" style="color: white;">〘 My Page 〙</h2><br>
        <% else %>
          <h2 class="font" style="color: white;">〘 User Page 〙</h2><br>
        <% end %>
      </div>
    </div>
    <div class='col-sm-12 text-center'>
      <p class="image">
        <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg", size: "200x200", class:"hover10 mt-3 rounded-circle"; %>
      </p>
    </div>
    <div class="col-sm-8 text-center mx-auto mt-4">
      <% if user_signed_in? && current_user.id.to_s == params[:id] %>
      <% else %>
        <tr>
          <div class="btn_design">
            <% if current_user.following?(@user) %>
              <%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          </div>
        </tr>
      <% end %>
      <div id="table">
        <table class='table table-bordered' style="margin-top: 10px;">
          <tr>
      	    <th class="table-dark" style="color: white;">ユーザー名</th>
      	    <td><%= @user.name %></td>
          </tr>
          <tr>
    	      <th class="table-dark" style="color: white;">自己紹介</th>
    	      <td><%= @user.introduction %></td>
          </tr>
          <tr>
            <th class="table-dark" style="color: white;">フォロー数</th>
            <td id="count"><%= link_to @user.followings.count, follows_user_path(@user) %></td>
          </tr>
          <tr>
            <th class="table-dark" style="color: white;">フォロワー数</th>
            <td><%= link_to @user.followers.count, followers_user_path(@user) %></td>
          </tr>
        </table>
      </div>
      <% if user_signed_in? && current_user.id.to_s == params[:id] %>
        <div class="btn_design">
          <%= link_to edit_user_path(@user), class: "btn btn-info col-md-6", method: :get do %>
           <i class="fas fa-cog"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if @posts.present? %>
      <div class="col-md-12 text-center mt-4" style="color: white;"><h5>〘 ユーザーの投稿 〙</h5></div>
      <%= render 'posts/post' %>
    <% else %>
      <div class="col-md-12 text-center mt-4" style="color: white;"><h5>〘 投稿がありません 〙</h5></div>
    <% end %>
  </div><br>
</div>