config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  attachment :image

  validates :image, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 500}
  validates :address, presence: true

  #住所から緯度と経度を計算
  geocoded_by :address
  after_validation :geocode

  def favorited_by?(post)
    favorites.where(post_id: post.id).exists?
  end

  def self.search(keyword)
    where(["title like? OR body like? OR address like?" , "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def save_posts(savepost_tags)
  # 現在のユーザーの持っているskillを引っ張ってきている
  current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
  # 今postが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
  old_tags = current_tags - savepost_tags
  # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
  new_tags = savepost_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tag_name:new_name)
      # 配列に保存
      self.tags << post_tag
    end
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tag.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  def user
  #インスタンスメソッドないで、selfはインスタンス自身を表す
    return User.find_by(id: self.user_id)
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/post_tag.rb
class PostTag < ApplicationRecord

  belongs_to :post
  belongs_to :tag

  validates :post_id,presence:true
  validates :tag_id,presence:true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :post_tags,dependent: :destroy
  has_many :posts, through: :post_tags

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :address])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
    @post_comment = PostComment.new
    @post_tags = @post.tags
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(",")
    if @post.save
      @post.save_posts(tag_list)
      redirect_to post_path(@post.id), success: '正常に投稿されました｡'
    else
      redirect_to posts_path, danger: '投稿に失敗しました'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, denger: '投稿が削除されました｡'
  end

  private

  def post_params
    params.require(:post).permit(:image, :address, :title, :body)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @posts = Post.all.search(params[:keyword]).order(created_at: :desc)
    @keyword = params[:keyword]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_puth(current_user)
    end
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), success: '会員情報が更新されました｡'
    else
      flash[:danger] = '会員情報の更新に失敗しました｡'
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reletionships_helper.rb
module ReletionshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="containar">
  <div class="row">
    <div class="col-md-12 text-center">
      <div id="slider">
        <div id="skippr-slider">
          <div class="image1"></div>
          <div class="image2"></div>
          <div class="image3"></div>
          <div class="image4"></div>
          <div class="image5"></div>
          <div class="image6"></div>
          <div class="image7"></div>
        </div>
      </div>
      <div class="about" style="color: #f8f8ff;">
        <p><b><h3>〘 世界各国の魅力を知りたい貴方様へ 〙</h3><br>
          <h5>
            この<i class="fas fa-globe"></i>Majestic Sights<i class="fas fa-globe"></i>では､<br>
            世界各国の魅力をシェアしあい､<br>
            皆様の行ってみたいを叶えます｡
          </h5>
          <%= image_tag "mj.png", alt: 'ロゴ画像', size: '400x200' %>
          <h4>
            日本から世界へ冒険しよう!!<br>
            Let's adventure from Japan to the world
          </h4><b>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="containar">
  <div class="row">
    <div class="col-md-12 text-center">
      <div id="slider">
        <div id="skippr-slider">
          <div class="image1"></div>
          <div class="image2"></div>
          <div class="image3"></div>
          <div class="image4"></div>
          <div class="image5"></div>
          <div class="image6"></div>
          <div class="image7"></div>
        </div>
      </div>
      <div class="fuwafuwa">
        <%= link_to home_about_path do %>
          <%= image_tag "mj.png", alt: 'ロゴ画像', size: '600x300' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, class: "keyword", placeholder: "キーワードを入力", value: @keyword, size: 30; %>
    <%= button_tag sanitize('<i class="fa fa-search"></i> Search '), :type => "submit", :class =>"btn btn-outline-light btn-md" %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @posts.present? %>
<div class="img2">
<% else %>
<div class="img">
<% end %>
  <div class="containar"><br>
    <div class="row">
      <div class="col-md-12 text-center">
        <% if @posts.present? %>
          <h2 class="font" style="color: white; margin-top: 50px;">〘 <%= @keyword %> の投稿が見つかりました｡ 〙</h2><br>
        <% else %>
          <h2 class="font" style="color: white; margin-top: 50px;">〘 <%= @keyword %> の投稿がありません｡ 〙</h2><br>
        <% end %>
      </div>
    </div>
    <% if @posts.present? %>
      <%= render "posts/post" %>
    <% else %>
    <% end %>
  </div><br>
</div>