config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :follows, :followers
    end
  end

  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  attachment :image

  validates :image, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 500}
  validates :address, presence: true

  #住所から緯度と経度を計算
  geocoded_by :address
  after_validation :geocode

  def favorited_by?(post)
    favorites.where(post_id: post.id).exists?
  end

  def self.search(keyword)
    where(["title like? OR body like? OR address like?" , "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def save_posts(savepost_tags)
  # 現在のユーザーの持っているskillを引っ張ってきている
  current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
  # 今postが持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
  old_tags = current_tags - savepost_tags
  # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
  new_tags = savepost_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(tag_name:new_name)
      # 配列に保存
      self.tags << post_tag
    end
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tag.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  def user
  #インスタンスメソッドないで、selfはインスタンス自身を表す
    return User.find_by(id: self.user_id)
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/post_tag.rb
class PostTag < ApplicationRecord

  belongs_to :post
  belongs_to :tag

  validates :post_id,presence:true
  validates :tag_id,presence:true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # class_name: "User"を定義することでUserテーブルのレコードを参照する

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :post_tags,dependent: :destroy
  has_many :posts, through: :post_tags

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
    @post_comment = PostComment.new
    @post_tags = @post.tags
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(",")
    if @post.save
      @post.save_posts(tag_list)
      redirect_to post_path(@post.id), success: '正常に投稿されました｡'
    else
      redirect_to posts_path, danger: '投稿に失敗しました'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, denger: '投稿が削除されました｡'
  end

  private

  def post_params
    params.require(:post).permit(:image, :address, :title, :body)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @posts = Post.all.search(params[:keyword]).order(created_at: :desc)
    @keyword = params[:keyword]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_puth(current_user)
    end
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), success: '会員情報が更新されました｡'
    else
      flash[:danger] = '会員情報の更新に失敗しました｡'
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reletionships_helper.rb
module ReletionshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div id="flash" class="col-md-12 text-center">
  <% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-expand-lg navbar-dark bg-dark" style="height: 80px;">
  <div class="col-md-12" style="text-align:center">
    <p class="footer-text"> © All rights reserved by Rintaro Matsumoto.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="btnshine" id="logo">
      <%= link_to root_path do %>
          <%= image_tag 'mj.png', size: '150x70'%>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " My Page", user_path(current_user.id), class: 'fas fa-user-cog nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " Post New", new_post_path, class: 'fas fa-plus-square nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " Posts List", posts_path, class: 'fas fa-passport nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton" style="text-center">
            <div class="text-center">
              <%= link_to " Sign Out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <div id="search">
            <div class="text-center">
              <%= render 'searches/form' %>
            </div>
          </div>
        <% else %>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " About", home_about_path, class: 'fas fa-info-circle nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " Sign Up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
          <li class="btn_design botton">
            <div class="text-center">
              <%= link_to " Sign In", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light btn btn-outline-light btn-block' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MajesticSights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheets" href="stylesheets/style.css" />
    <link rel="stylesheets" href="stylesheets/skippr.css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0b305dc30a.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="flash"><%= render 'layouts/flash' %></div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>